### PR TITLE
APP-193: Sample apps fixes after change: CTL in Events extension

### PR DESCRIPTION
**Pull request by nocs00**

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by ashvayka** [comment]
LGTM

**Comment by nocs00** [comment]
@kaa-leeroy retest this please

**Comment by rasendubi** [comment]
@kaa-leeroy add to whitelist

**Comment by nocs00** [comment]
@kaa-leeroy add to whitelist

**Comment by vadimol** [comment]
See Travis log
https://travis-ci.org/kaaproject/sample-apps/builds/155014612

**Pull request merged**
