### PR TITLE
APP-349: [C] Validate sample applications

### PR DESCRIPTION
**Pull request by Dubland**
/cc @Slash32 @vadimol

### CODE REVIEW

**Comment by Dubland** [comment]
test this please

**Comment by Dubland** [comment]
@kaa-leeroy test this please

**Comment by Dubland** [comment]
@kaa-leeroy retest this please

**Review by Slash32 — CHANGES_REQUESTED** [review]
The PR does not pass Jenkins: https://jenkins.kaaproject.org:52001/job/KSAs_test_sample_apps_pr/25/console

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Review by Slash32 — APPROVED** [review]

**Pull request merged**
