### PR TITLE
APP-310: Fixed license check issues

### PR DESCRIPTION
**Pull request by Slash32**
Also dropped occasionally merged files.

### CODE REVIEW

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Review by vadimol — APPROVED** [review]
LGTM

**Comment by vadimol** [comment]
FYI:
The "xcuserdatad" directories are also located in credentials and iotworld demos:

_./credentialsdemo/source/objc/CredentialsDemo.xcodeproj/xcuserdata/agutyro.xcuserdatad/xcschemes/CredentialsDemo.xcscheme
./credentialsdemo/source/objc/CredentialsDemo.xcodeproj/xcuserdata/agutyro.xcuserdatad/xcschemes/xcschememanagement.plist_

_./iotworld/source/smarthome/ios/SmartHouse.xcodeproj/xcuserdata/abohomol.xcuserdatad/xcschemes/SmartHouse.xcscheme
./iotworld/source/smarthome/ios/SmartHouse.xcodeproj/xcuserdata/abohomol.xcuserdatad/xcschemes/xcschememanagement.plist_

**Comment by Slash32** [comment]
Thanks for the information regarding other stale files. I've created APP-324 for tracking them.

**Pull request merged**
