### PR TITLE
APP-350: [C++] DataCollection Demo: fix assmebly/src-cpp.xml

### PR DESCRIPTION
**Pull request by RostakaGmfun**
/cc @Slash32

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by Slash32** [comment]
@kaa-leeroy test this hard please

**Comment by Slash32** [comment]
add to whitelist

**Comment by Slash32** [comment]
@kaa-leeroy test this hard please

**Comment by Slash32** [comment]
@kaa-leeroy test this hard please

**Review by Slash32 — APPROVED** [review]

**Pull request merged**
