### PR TITLE
APP-152: [C++] Basic level Apps: Notifications - Reviewed

### PR DESCRIPTION
**Pull request by hunch7**
APP-152: [C++] Basic level Apps: Notifications - Reviewed

### CODE REVIEW

**Comment by Oldnickus** [comment]
@kaa-leeroy ok to test

**Comment by Oldnickus** [comment]
@kaa-leeroy ok to test

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Oldnickus** [comment]
test this please

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by vadimol** [comment]
test this please

**Comment by vadimol** [comment]
@kaa-leeroy test this please

**Comment by vadimol** [comment]
@kaa-leeroy test this please

**Comment by vadimol** [comment]
@kaa-leeroy retest this please

**Comment by vadimol** [comment]
@kaa-leeroy retest this please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please _or die_

**Comment by vadimol** [comment]
Looks good for me

**Pull request merged**
