### PR TITLE
DONT MERGE2

### PR DESCRIPTION
**Pull request by akokhanovskyi**

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by rasendubi** [comment]
@kaa-leeroy add to whitelist

**Comment by akokhanovskyi** [comment]
@kaa-leeroy test this fully please

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Pull request closed without merging**
