### PR TITLE
APP-483: Configure telemetry monitor and server scheme

### PR DESCRIPTION
**Pull request by odovhai**

### CODE REVIEW

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Oldnickus** [comment]
retest this please

**Comment by Slash32** [comment]
test this fully please

**Comment by Oldnickus** [comment]
@kaa-leeroy retest this please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this fully please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Pull request closed without merging**
