### PR TITLE
APP-514: [C] Incorrect output message in verifiers demo

### PR DESCRIPTION
**Pull request by Dubland**
/cc @Slash32

### CODE REVIEW

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Dubland** [comment]
@kaa-leeroy test this please

**Comment by Dubland** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Dubland** [comment]
@kaa-leeroy test this please

**Comment by Dubland** [comment]
@kaa-leeroy test this please

**Review by sparadiuk — APPROVED** [review]

**Comment by sparadiuk** [comment]
It looks like correct, if take a look in the code

**Pull request merged**
