### PR TITLE
APP-208 Drop the obsolete sample apps [activation demo]

### PR DESCRIPTION
**Pull request by maxml**
http://jira.kaaproject.org/browse/APP-208

### CODE REVIEW

**Comment by krupet** [comment]
LGTM

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by Slash32** [comment]
test this please

**Comment by Oldnickus** [comment]
@kaa-leeroy add to whitelist

**Comment by Slash32** [comment]
test this please

**Comment by Oldnickus** [comment]
@kaa-leeroy retest this please

**Comment by Slash32** [comment]
@kaa-leeroy retest this please

**Comment by Slash32** [comment]
@kaa-leeroy retest this please

**Comment by Oldnickus** [comment]
@kaa-leeroy retest this please

**Pull request merged**
