### PR TITLE
KSB-26: Added 2 logs for further investigation

### PR DESCRIPTION
**Pull request by odovhai**

### CODE REVIEW

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by odovhai** [comment]
@kaa-leeroy test this please

**Comment by odovhai** [comment]
@kaa-leeroy test this please

**Comment by odovhai** [comment]
@kaa-leeroy test this please

**Comment by odovhai** [comment]
@kaa-leeroy test this please

**Comment by odovhai** [comment]
@kaa-leeroy test this please

**Comment by odovhai** [comment]
@kaa-leeroy test this please

**Comment by odovhai** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by odovhai** [comment]
@kaa-leeroy test this please

**Comment by odovhai** [comment]
@kaa-leeroy test this please

**Comment by odovhai** [comment]
@kaa-leeroy test this please

**Comment by odovhai** [comment]
@kaa-leeroy test this please

**Review by Slash32 — APPROVED** [review]

**Pull request merged**
