### PR TITLE
APP-406: Fix Profiling and grouping demos description

### PR DESCRIPTION
**Pull request by am1kk**
http://jira.kaaproject.org/browse/APP-406

Merge of #534 to 'master' branch

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by Slash32** [comment]
@kaa-leeroy add to whitelist

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by am1kk** [comment]
@kaa-leeroy test this please

**Review by Slash32 — APPROVED** [review]

**Pull request merged**
