### PR TITLE
APP-422: Change EventClassFamilyDto in Event demo builder

### PR DESCRIPTION
**Pull request by odovhai**

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by Slash32** [comment]
@kaa-leeroy add to whitelist

**Comment by Slash32** [comment]
@kaa-leeroy add to whitelist

**Comment by Slash32** [comment]
@kaa-leeroy add to whitelist

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Review by Slash32 — APPROVED** [review]

**Pull request merged**
