### PR TITLE
APP-334: [C++] Include Endpoint Ownership Demo to sandbox

### PR DESCRIPTION
**Pull request by Dubland**
/cc @vadimol @Slash32

### CODE REVIEW

**Review by Slash32 — APPROVED** [review]

**Comment by Dubland** [comment]
@kaa-leeroy test this please

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by Dubland** [comment]
@kaa-leeroy retest this please

**Comment by Dubland** [comment]
test this please

**Review by Slash32 — APPROVED** [review]

**Pull request merged**
