### PR TITLE
APP-329: [C/C++] Distinguish between CMake variables and compile definitions in cmakegen

### PR DESCRIPTION
**Pull request by RostakaGmfun**
/cc @Slash32

### CODE REVIEW

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Comment by RostakaGmfun** [comment]
@kaa-leeroy test this fully please

**Comment by RostakaGmfun** [comment]
@kaa-leeroy test this fully please

**Comment by RostakaGmfun** [comment]
@kaa-leeroy test this fully please

**Comment by RostakaGmfun** [comment]
@kaa-leeroy test this fully please

**Comment by RostakaGmfun** [comment]
@kaa-leeroy test this fully please

**Comment by Slash32** [comment]
@GamovCoder please review

**Comment by Slash32** [comment]
@vadimol Please review

**Pull request closed without merging**
