### PR TITLE
APP-335: [C] Include Endpoint Ownership demo to sandbox

### PR DESCRIPTION
**Pull request by Dubland**
/cc @Slash32 @vadimol

### CODE REVIEW

**Review by Slash32 — CHANGES_REQUESTED** [review]
This needs to await Sandbox build with an additional test pass on it.

**Comment by Dubland** [comment]
test this please

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by Dubland** [comment]
test this please

**Comment by Dubland** [comment]
test this please

**Comment by Dubland** [comment]
test this please

**Comment by Dubland** [comment]
@kaa-leeroy  test this please

**Comment by Dubland** [comment]
@kaa-leeroy retest this please

**Comment by Dubland** [comment]
test this please

**Review by Slash32 — APPROVED** [review]
The <platforms> tag is empty but should have been filled correctly for the Sandbox operation.

Will add later. Approving for merge now.

**Pull request merged**
