### PR TITLE
APP-69: [Java] Kaa client can't resumes at once after starting

### PR DESCRIPTION
**Pull request by Acarus**

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Acarus** [comment]
@kaa-leeroy retest this please

**Comment by Acarus** [comment]
@kaa-leeroy retest this please

**Comment by ikulikov** [comment]
@kaa-leeroy retest this please

**Comment by Oldnickus** [comment]
@kaa-leeroy retest this please

**Pull request merged**
