### PR TITLE
APP-495: Absence of targets directory in CDataCollection demo

### PR DESCRIPTION
**Pull request by Dubland**
/cc @Slash32 @RostakaGmfun

### CODE REVIEW

**Review by RostakaGmfun — APPROVED** [review]

**Review by Slash32 — APPROVED** [review]

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Pull request merged**
