### PR TITLE
APP-146: Duplicate license in cassandra and storm demos

### PR DESCRIPTION
**Pull request by RostakaGmfun**
/cc @Dubland

### CODE REVIEW

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Dubland** [comment]
LGTM

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by vadimol** [comment]
Jenkins is not stable now and does not provide reliable results.
Looks good for me.

**Pull request merged**
