### PR TITLE
Uncomment lines about android demo in builder

### PR DESCRIPTION
**Pull request by antonshkurenko**

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by Slash32** [comment]
Add to whitelist

**Review by Slash32 — APPROVED** [review]
LGTM, but let's pass Jenkins

**Review by Slash32 — CHANGES_REQUESTED** [review]
+

**Review by Slash32 — APPROVED** [review]

**Pull request merged**
