### PR TITLE
APP-400: Add possibility to ignore tests in apptester

### PR DESCRIPTION
**Pull request by mariangavlytskiy**
1) Added possiblity to exempt tests
2) Updated output

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by Oldnickus** [comment]
@kaa-leeroy add to whitelist

**Comment by vadimol** [comment]
@kaa-leeroy test this fully please

**Comment by vadimol** [comment]
@kaa-leeroy test this fully please

**Review by vadimol — APPROVED** [review]
Overall, looks good to me

**Comment by vadimol** [comment]
@kaa-leeroy test this fully please

**Review by Slash32 — APPROVED** [review]

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Comment by vadimol** [comment]
@kaa-leeroy test this fully please

**Pull request merged**
