### PR TITLE
APP-440: update build tools versions

### PR DESCRIPTION
**Pull request by antonshkurenko**

### CODE REVIEW

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Comment by antonshkurenko** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@tonyshkurenko this was merged in re-based version as #495 . Closing the PR.

**Pull request closed without merging**
