### PR TITLE
APP-143 - Android sample "Notification"  ONLY code

### PR DESCRIPTION
**Pull request by maxml**
http://jira.kaaproject.org/browse/APP-143

### CODE REVIEW

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by vadimol** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Pull request closed without merging**
