### PR TITLE
KSB-23: Generate pom.xml in sandbox-builder

### PR DESCRIPTION
**Pull request by antonshkurenko**

### CODE REVIEW

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
This is now replaced by #491

**Pull request closed without merging**
