### PR TITLE
APP-336: 500 Server Error while loading sandbox filters on UI

### PR DESCRIPTION
**Pull request by vasner**
Fix "projects.xml"s with empty Features, Sdk Language, Platforms or Complexity fields;

Review: @Slash32, @pyshankov and @ashvayka

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by Slash32** [comment]
Add to whitelist

**Review by Slash32 — APPROVED** [review]
Approved, but let the PR pass Jenkins

**Comment by Slash32** [comment]
@kaa-leeroy test this hard please

**Comment by Slash32** [comment]
@kaa-leeroy test this hard please

**Pull request merged**
