### PR TITLE
APP-374: Add events demo for android

### PR DESCRIPTION
**Pull request by antonshkurenko**

### CODE REVIEW

**Comment by antonshkurenko** [comment]
New pr instead of the #366 and #339

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Review by Slash32 — APPROVED** [review]

**Pull request merged**
