### PR TITLE
APP -510: Fixed output table with results.[release 2.0] 

### PR DESCRIPTION
**Pull request by mariangavlytskiy**

### CODE REVIEW

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Review by vadimol — APPROVED** [review]

**Review by Slash32 — APPROVED** [review]

**Pull request merged**
