### PR TITLE
APP-524: Fix build.sh scripts for C demo

### PR DESCRIPTION
**Pull request by Dubland**
/cc @Slash32

### CODE REVIEW

**Comment by Dubland** [comment]
@kaa-leeroy test this please

**Comment by Dubland** [comment]
@kaa-leeroy retest this please

**Comment by Dubland** [comment]
@kaa-leeroy test this please

**Comment by Dubland** [comment]
@kaa-leeroy test this please

**Comment by Dubland** [comment]
@test this hard please

**Comment by Dubland** [comment]
@kaa-leeroy test this please

**Comment by Dubland** [comment]
@kaa-leeroy test this please

**Comment by Dubland** [comment]
@kaa-leeroy retest this please

**Review by Slash32 — APPROVED** [review]

**Pull request merged**
