### PR TITLE
APP-374: Add events demo for android

### PR DESCRIPTION
**Pull request by Slash32**
See #339 for the original PR.

### CODE REVIEW

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Comment by Slash32** [comment]
This PR requires update accordingly to the comments to #339 and related change to the Sandbox builder.

**Comment by antonshkurenko** [comment]
Opened new pr for this #367 :|

**Comment by Slash32** [comment]
PR is deprecated. Closing.

**Pull request closed without merging**
