### PR TITLE
APP-446: Build failure on Travis due to rat-check issues

### PR DESCRIPTION
**Pull request by am1kk**
http://jira.kaaproject.org/browse/APP-446

### CODE REVIEW

**Comment by am1kk** [comment]
@kaa-leeroy test this fully please

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Comment by Slash32** [comment]
@kaa-leeroy test this fully please

**Review by Slash32 — APPROVED** [review]

**Pull request merged**
