### PR TITLE
APP-66 Integrate Nix into sample apps

### PR DESCRIPTION
**Pull request by Dubland**
except gpio demo for esp8266
/cc @rasendubi @RostakaGmfun

### CODE REVIEW

**Comment by Oldnickus** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by rasendubi** [comment]
@kaa-leeroy add to whitelist

**Comment by Slash32** [comment]
LGTM

**Pull request merged**
