### PR TITLE
APP-480: [C++] Fix credentials demo

### PR DESCRIPTION
**Pull request by Dubland**
/cc @Slash32

### CODE REVIEW

**Comment by Dubland** [comment]
@kaa-leeroy test this please

**Comment by Dubland** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Dubland** [comment]
@kaa-leeroy test this please

**Review by sparadiuk — APPROVED** [review]

**Review by ohamov — APPROVED** [review]

**Comment by Dubland** [comment]
@kaa-leeroy test this please

**Pull request merged**
