### PR TITLE
APP-496: Use common/build-scripts/build.sh for cassandra demo

### PR DESCRIPTION
**Pull request by RostakaGmfun**
/cc @Slash32

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by Slash32** [comment]
@kaa-leeroy add to whitelist

**Review by Slash32 — APPROVED** [review]

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Comment by Slash32** [comment]
@kaa-leeroy test this please

**Pull request merged**
