### PR TITLE
App 527 [C] Update the cmake_minimum_required statement for C SDK Sample appllications

### PR DESCRIPTION
**Pull request by sparadiuk**
…ations

### CODE REVIEW

**Review by Slash32 — APPROVED** [review]

**Review by Slash32 — CHANGES_REQUESTED** [review]
Please do not add any generic configuration to the applications cmake files. All the generic part has already moved to /common and that is the only correct place to change or add such generic things.

**Comment by vadimol** [comment]
@kaa-leeroy retest this please

**Comment by sparadiuk** [comment]
Checked, it looks ok.
Returned, changed files only in the common/ folder.

**Comment by Dubland** [comment]
@kaa-leeroy test this please

**Comment by vadimol** [comment]
@Dubland , please review

**Review by Dubland — APPROVED** [review]

**Review by vadimol — APPROVED** [review]

**Pull request merged**
