### PR TITLE
APP-376: Update user verifiers demo credentials configuration

### PR DESCRIPTION
**Pull request by am1kk**
http://jira.kaaproject.org/browse/APP-376

### CODE REVIEW

**Comment by kaa-leeroy** [comment]
Can one of the admins verify this patch?

**Comment by am1kk** [comment]
@rib47 Review please.
@Slash32 Add to whitelist please.

**Comment by Slash32** [comment]
Add to whitelist

**Comment by Rib47** [comment]
LGTM

**Review by Slash32 — APPROVED** [review]

**Comment by Rib47** [comment]
I have checked changes in Builder - all works fine.

**Pull request merged**
